version: '3'

services:

  nginx:
    container_name: nginx
    build: 
      context: nginx
    volumes:
      - web_data:/var/www
    networks:
      - net
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: 
      context: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped 
    networks:
      - net
    environment:
      MARIADB_ROOT_PASSWORD: somewordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress

  wordpress:
    container_name: wordpress
    build: 
      context: wordpress
    depends_on:
      - mariadb
      - nginx
    ports:
      - "8000:80"
    restart: unless-stopped
    networks:
      - net
    volumes:
      - web_data:/var/ww  w
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_URL: dthalman.42.fr
      WORDPRESS_TITLE: Inception
      WORDPRESS_ADMIN_USER: wordpress
      WORDPRESS_ADMIN_PASSWORD: wordpress
      WORDPRESS_ADMIN_EMAIL: admin@student.42lausanne.ch
      WORDPRESS_USER: wordpress
      WORDPRESS_USER_EMAIL: dthalman@student.42lausanne.ch
      WORDPRESS_USER_PASSWORD: wordpress

# il n'est pas nécessaire de défini un réseau. 
# Il y en a un qui est créé automatiquement sous le nom de myapp_default

networks:
  net:

# https://docs.docker.com/compose/compose-file/#volumes

volumes:
  db_data:
    driver: local
    driver_opts:
      device: ~/database
      type: volume
  web-data:
    driver: local
    driver_opts:
      device: ~/wordpress
      type: volume