version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: ./nginx
    volumes:
      - web_data:/var/www:rw
    networks:
      - net
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb
    build: 
      context: ./mariadb
    volumes:
      - db_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: unless-stopped 
    networks:
      - net
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD} 
      MARIADB_DATABASE: ${MARIADB_DATABASE} 
      MARIADB_USER: ${MARIADB_USER} 
      MARIADB_PASSWORD: ${MARIADB_PASSWORD} 

  wordpress:
    container_name: wordpress
    image: wordpress
    build: 
      context: ./wordpress
    volumes:
      - web_data:/var/www:rw
    depends_on:
      - mariadb
      - nginx
    ports:
      - "8000:80"
    restart: unless-stopped
    networks:
      - net
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}

# il n'est pas nécessaire de défini un réseau. 
# Il y en a un qui est créé automatiquement sous le nom de myapp_default

networks:
  net:

# https://docs.docker.com/compose/compose-file/#volumes

volumes:
  db_data:
    driver: local
    driver_opts:
      device: '${DB_VOLUME}'
      type: volume
      o: bind
  web_data:
    driver: local
    driver_opts:
      device: '${WEB_VOLUME}'
      type: volume
      o: bind